apiVersion: v1
kind: Namespace
metadata:
  name: harness-test
  labels:
    tier: backend
    environment: dev
---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx-test
      namespace: harness-test
      labels:
        tier: backend
        environment: dev
        #aadpodidbinding: __serviceName__
        version: v1
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: nginx
          tier: backend
          environment: dev
          version: v1
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: nginx
            tier: backend
            environment: dev
            #aadpodidbinding: __serviceName__
            version: v1
        spec:
          #serviceAccountName: backend-__serviceName__
          containers:
          - name: nginx123
            image: vjharnessacr.azurecr.io/nginx-harness:1.23.3
            imagePullPolicy: IfNotPresent
            resources:
              requests:
               #cpu: ".1"
               memory: "256M"
              limits:
               cpu: ".5"
               memory: "500M"
            ports:
            - containerPort: 443
          restartPolicy: Always
          # imagePullSecrets:
          # - name: __ImagePullSecretName__
    
